Blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from Index.views import index as i

app_name = "Blog"

urlpatterns=[
    url(r'^settings/$', views.settings, name="settings"),
    
]

urlpatterns+=[
    path('blogDetail/(?P<blogId>\d+)/', views.blogDetail, name='blogDetail'),
    path('new_post/', views.new_post, name='new_post'),

    path('edit_post/<blogpost_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>/', views.delete_post, name='delete_post'),


    path('edit_post/<blogpost_id>', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>', views.delete_post, name='delete_post'),
    path('simple_search/', views.simple_search, name='simple_search'),

]

SmartTravel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('Index.urls')),
    url(r'^blog/', include('Blog.urls')),
    url(r'^query/', include('Query.urls')),
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()
    date_pub = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    #ispublic=models.BooleanField(default=True)

    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)

    def __str__(self):
        '''Returns string representation of BlogPost model'''
        return self.title[:50]

class BlogComment(models.Model):
    content = models.TextField(max_length=200)
    date_pub = models.DateTimeField(auto_now_add=True)
    blogPost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    def __str__(self):
        '''Returns string representation of BlogComment model'''
        return self.content[:50]



class Blog_Search(models.Model):
    search_name=models.CharField(max_length=30) # kaslai search gareko
    viewer_id=models.IntegerField() # kasle search gareko
    searched_date = models.DateTimeField(auto_now_add=True)

Blog/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content']

Blog/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from django.http import Http404
import os
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import BlogPostForm
from .simle_search import get_query

# Create your views here.

def settings(request):
    template_path = "Blog/settings.html"
    return render(request, template_path)

# Create your views here.
def index(request):

    blogPosts = BlogPost.objects.order_by('-date_pub')
    context = {'blogPosts': blogPosts}

    template_path="Blog/index.html"
    return render(request, template_path, context)

def blogDetail(request, blogId):

    blog = BlogPost.objects.get(id=blogId)
    context = {'blog': blog}
    return render(request, 'Blog/blogDetail.html', context)


@login_required
def new_post(request):
    '''ADd a new post'''
    if(request.method != 'POST'):
        form = BlogPostForm()
    else:
        form = BlogPostForm(request.POST)
        if(form.is_valid()):
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'form': form}
    return render(request, 'Blog/new_post.html', context)

@login_required
def edit_post(request, blogpost_id):
    '''Edit an existing post'''
    blogpost = BlogPost.objects.get(id=blogpost_id)
    if(blogpost.owner != request.user):
        raise Http404

    title = blogpost.title
    content = blogpost.content

    if request.method != 'POST':
        form = BlogPostForm(instance=blogpost)
    else:
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'form': form, 'blogpost': blogpost}
    return render(request, 'Blog/edit_post.html', context)


@login_required
def delete_post(request, blogpost_id):

    blogpost = BlogPost.objects.get(id=blogpost_id)

    if(blogpost.owner != request.user):
        raise Http404
    else:
        blogpost.delete()

    return redirect('Blog:index')


@login_required
def simple_search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']

        entry_query = get_query(query_string, ['title', 'content', ])

        found_entries = BlogPost.objects.filter(entry_query).order_by('-date_pub')

        context = {'query_string': query_string, 'found_entries': found_entries}
    return render(request, 'Blog/search_results.html', context)

Blog/templates/Blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-home.css' %} " rel="stylesheet">
      <script src="{% static 'js/blog-home.js' %} "></script>

  </head>
  <body class="body">
    {% if user.is_authenticated %}
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

    {% else %}
    <p><a href="/index/">Login</a></p><!-- go back to 'index/index.hmtl' page-->
    <p><a href="/index/register">Register</a></p>
    {% endif %}

  </body>
</html>

Blog/templates/Blog/blogDetail.html
{% extends 'Blog/base.html' %}

{% block content %}

    <!-- Facebook Plugin -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.0';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    <h2>{{ blog.title }} </h2>

    <p>{{ blog.content|linebreaks }}</p>

    <button type="button" class="btn btn-primary">
      Likes <span class="badge badge-light">{{ blog.likes }}</span>
      <span class="sr-only">blog likes</span>
    </button>

    <button type="button" class="btn btn-primary">
      Dislikes <span class="badge badge-light">{{ blog.dislikes }}</span>
      <span class="sr-only">blog dislikes</span>
    </button>

    <br>
    <div>
    <h4>Comments:</h4>

    <!-- <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div> -->

    <div class="fb-comments" data-href="https://smarttravel.com/blog/blogdetail/{{ blog.id }}" data-numposts="5"></div>


        {% comment %} <div class="fb-comments" data-href="SmartTravel/Blog/blogDetail" data-numposts="8"></div>
{% endcomment %}

    <ul>
        {% for comment in blog.blogcomment_set.all %}
            <li>{{ comment.date_pub }}<br>{{ comment.content }}</li>
            <br>
        {% endfor %}
    </ul>
    </div>

{% endblock %}

Blog/templates/Blog/edit_post.html
{% extends 'Blog/base.html' %}

{% block header %}

    <br>
	<h4 class="lead">Edit your blog post:</h4>
	<hr class="my-4">

{% endblock header %}

{% block content %}

    <form action="{% url 'Blog:edit_post' blogpost.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="btn btn-success">Save Changes</button>
    </form>

{% endblock content %}

Blog/templates/Blog/index.html
{% extends 'Blog/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="container">

    <!-- sidenav-->
    <div id="mySidenav" class="sidenav ">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="#">Profile</a>
        <a href="#">Your Blog</a>
        <a href="#">Tour Diary </a>
        <a href="#">Followers</a>
        <a href="#">Followings</a>
        <a href="#">Settings</a>
    </div>

<div id="main">
    <!-- Navigation -->
<<<<<<< HEAD
    <div class="class-nav">
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a href="#" onclick="openNav();" ><img id="profile"  class="card-img-left border" src="{% static 'images/shristi.jpg' %}" style="width:56px; border-radius: 50%" alt="profile" ></a>
          
          <!-- for three line button when window size is smaller -->
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-expanded controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- for top-right nav bar -->
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto" id="top_nav_bar">
              <li class="nav-item">
                <a class="nav-link" href="/blog">Home
                  <span class="sr-only"> (current)</span>
                </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/query">GoTour</a><!-- go to query/index.html page  defined in Query app-->
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="settings">Settings</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/index/logout">LogOut</a><!-- logout url pattern defined in Index app -->
              </li>
            </ul>
          </div>
        </div>
      </nav>
=======
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="row">
            <div class="col-2" id="left_nav">
                <div class="container" id="nav_container">
                    <div class="row">
                        <div class="col-6" >
                            <img id="profile"  class="card-img-left border" src="{% static 'images/shristi.jpg' %}" style="width:56px; border-radius: 50%" alt="profile" >
                        </div>
                            <div class="col-6" >
                                <!-- Use any element to open the sidenav -->
                                <a href="#" onclick="openNav()" ><p class="h3"><small class="text-muted"> Profile </small></p></a>
                            </div>
                    </div>
                </div>
            </div>
            <div class="col-10" id="right_nav">
                <div class="container "  id="nav_container" >
                      <div class="collapse navbar-collapse" id="navbarResponsive" >
                          <ul class="navbar-nav ml-auto" id="top_nav_bar">
                                <li class="nav-item active">
                                  <a class="nav-link" href="/blog">Home
                                    <span class="sr-only">(current)</span>
                                  </a>
                                </li>
                                <li class="nav-item active">
                                  <a class="nav-link" href="/query">GoTour</a><!-- go to query/index.html page  defined in Query app-->
                                </li>
                                <li class="nav-item active">
                                  <a class="nav-link" href="settings">Settings</a>
                                </li>

                              <li class="nav-item active" style="color: white;">
                                  <span>{{user.username}}</span><!-- logout url pattern defined in Index app -->
                                </li>

                                <li class="nav-item active">
                                  <a class="nav-link" href="/index/logout">LogOut</a><!-- logout url pattern defined in Index app -->
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>


    <div class="float-md-left">
    <br>
    <!--new post-->
    <p><a class="btn btn-outline-primary" href="{% url 'Blog:new_post' %}">create a new post</a></p>
    <br>
    <p><a href="/index">Login</a></p><!-- go back to 'index/index.hmtl' page-->
    <p><a href="/index/register">Register</a></p>
>>>>>>> 76b5ae030a88b01cb19a592c143f755662f638f3
    </div>


<!--<div class="float-right"> -->
    <!-- Page Content -->
    <div class="container">
        <div class="row">
         
        <!-- Blog POST Column -->
        <div class="col-md-8">
          <div class="float-center">
            <br>
              <!--new post here-->
              <a href="{% url 'Blog:new_post' %}">Add Post</a>
            <br>
          </div>
{% for blog in blogPosts %}
          <!-- Blog Posts -->
          <div class="card bg-light mb-3 border-dark mb-3" id=" blog-card">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{ blog.title }}</h2>
              <p class="card-text">{{ blog.content|truncatechars:50 }}</p>
              <a href="{% url 'Blog:blogDetail' blog.id %}" class="btn btn-primary">Read More &rarr;</a>

              {% if blog.owner != user %}
                <a href="{% url 'Blog:edit_post' blog.id %}" class="btn btn-dark card-link">Edit Post &rarr;</a>
                <a href="{% url 'Blog:delete_post' blog.id %}" class="btn btn-dark">Delete Post</a>
              {% else %}
                <a href="{% url 'Blog:edit_post' blog.id %}" class="btn btn-primary card-link">Edit Post &rarr;</a>
                <a href="{% url 'Blog:delete_post' blog.id %}" class="btn btn-default"><span class="glyphicon glyphicon-remove">Delete Post</span></a>
              {% endif %}
            </div>
            <div class="card-footer text-muted">
              Posted on {{ blog.date_pub.date }} by
              <a href="#">{{ blog.owner }}</a>
            </div>
          </div>

{% endfor %}

          <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item ">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md -4">

          <!-- Search Widget -->
          <div class="card my-4 border-dark">
            <h5 class="card-header">Search </h5>
            <div class="card-body">
              <div class="input-group">
                <form method="get" action="{% url 'Blog:simple_search' %}" accept-charset="utf-8" class="form-inline my-2 my-lg-0">
					<input type="search" name="q" placeholder="Search blog" aria-label="Search" class="form-control mr-sm-2">
					<button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
				</form>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4 border-dark">
            <h4 class="card-header">Notifications</h4>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Comment from Shristi...</a>
                    </li>
                    <li>
                      <a href="#">Recommendations...</a>
                    </li>
                    <li>
                      <a href="#">Trip Offers...</a>
                    </li>
                    <li>
                      <a href="#">Places your friends posted...</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4 border-dark">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              When hovered over a blog, show profile about person who posted here.
            </div>
          </div>

        </div>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-3 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white" id="footer-copyright"></p>

      </div>
      <!-- /.container -->
    </footer>
    </div>
    </div>

<<<<<<< HEAD
=======
    <script>
        var d = new Date();
        document.getElementById("footer-copyright").innerHTML = "" +
            "Copyright &copy; Smart Travel (" + d.getFullYear() + ")";
    </script>

>>>>>>> 76b5ae030a88b01cb19a592c143f755662f638f3
{% endblock %}

Blog/templates/Blog/new_post.html
{% extends 'Blog/base.html' %}

{% block header %}

    <br>
	<h4 class="lead">Create a new post:</h4>
	<hr class="my-4">

{% endblock %}

{% block content %}

	<form action="{% url 'Blog:new_post' %}" method="post" class="form">
		{% csrf_token %}
		{{ form.as_p }}

		<button class="btn btn-primary" name="submit">add post</button>

	</form>

{% endblock content %}

Blog/templates/Blog/search_results.html
{% extends 'Blog/base.html' %}

{% block header %}
	<hr class="my-4">
	<h3 class="lead">Search results for "{{ query_string }}"" :</h3>
	<hr class="my-4">
{% endblock header %}

{% block content %}

	{% for blogpost in found_entries %}
		<div class="card bg-light mb-3">
			<div class="card-header">
				<small>{{ blogpost.date_pub }}</small>
			</div>
			<div class="card-body">
				<h3 class="card-title text-primary">
					{{ blogpost.title }}
				</h3>
				<div class="card-text text-secondary">
					{{ blogpost.content|truncatechars:50 }}
				</div>

                <a class="card-link" href="{% url 'Blog:blogDetail' blogpost.id %}">Read more</a>
				<a class="card-link" href="{% url 'Blog:edit_post' blogpost.id %}">edit post</a>
                <a class="card-link" href="{% url 'Blog:delete_post' blogpost.id %}">delete post</a>
			</div>
		</div>
	{% empty %}
		<h4 class="lead">Cannot find any results.</h4>
	{% endfor %}

{% endblock content %}

Blog/templates/Blog/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Settings</title>
</head>
<body>

</body>
</html>